"use client"

// import React from 'react';
// import { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import Navbar from '@/app/components/navbar/Navbar';
// import Link from 'next/link';
// const inter = Inter({ subsets: ['latin'] });
// import { LocalizationProvider } from '@mui/x-date-pickers';
// import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

// // export const metadata: Metadata = {
// //   title: 'Create Next App',
// //   description: 'Generated by create next app',
// // };



// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <LocalizationProvider dateAdapter={AdapterDayjs}>
//     <html lang="en">
//       <body className={inter.className}>
       
//         <Navbar />
//         <div className='navbar'>
//           <Link href="/check-in" className='tab'>Check-In</Link>
//           <Link href="/strippingout" className='tab'>Stripping Out</Link>
//           <Link href="/loading" className='tab'>Loading</Link>
//         </div>
//         {children}
   
//       </body>
//     </html>
//     </LocalizationProvider>
//   );
// }

// layout.tsx
import React from 'react';
import Navbar from '@/app/ui/navbar';
import Link from 'next/link';
import { inter} from '@/app/ui/fonts';
import './globals.css';
import { Provider } from './components/Provider';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    
    <LocalizationProvider dateAdapter={AdapterDayjs}>
     
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
          <Provider>
            <Navbar />
            
            {children}
            </Provider>
          </body>
        </html>

</LocalizationProvider>

  );
}
